# Generated by Django 3.1.3 on 2021-01-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('blogName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.blogs')),
            ],
        ),
    ]
