# Generated by Django 3.1.3 on 2021-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Blog_Thumbnails', verbose_name='thumnbail'),
        ),
    ]
